service: fitness-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-central-1

# 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create_exercise.js
  # - path: url path is /exercises
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  createExercise:
    handler: create_exercise.main
    events:
      - http:
          path: exercises
          method: post
          cors: true
          authorizer: aws_iam
  getExercises:
      # Defines an HTTP API endpoint that calls the main function in get.js
      # - path: url path is /exercises/{id}
      # - method: GET request
      handler: get_exercise.main
      events:
      - http:
          path: exercises/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listExercises:
      # Defines an HTTP API endpoint that calls the main function in list.js
      # - path: url path is /exercises
      # - method: GET request
      handler: list_exercises.main
      events:
        - http:
            path: exercises
            method: get
            cors: true
            authorizer: aws_iam
  updateExercise:
      # Defines an HTTP API endpoint that calls the main function in update.js
      # - path: url path is /exercises/{id}
      # - method: PUT request
      handler: update_exercise.main
      events:
        - http:
            path: exercises/{id}
            method: put
            cors: true
            authorizer: aws_iam
  deleteExercise:
      # Defines an HTTP API endpoint that calls the main function in delete.js
      # - path: url path is /exercises/{id}
      # - method: DELETE request
      handler: delete_exercise.main
      events:
        - http:
            path: exercises/{id}
            method: delete
            cors: true
            authorizer: aws_iam