service: fitness-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-central-1

# 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in exercise_create.js
  # - path: url path is /exercises
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  createExercise:
    handler: exercise_create.main
    events:
      - http:
          path: exercises
          method: post
          cors: true
          authorizer: aws_iam
  getExercises:
      # Defines an HTTP API endpoint that calls the main function in get.js
      # - path: url path is /exercises/{id}
      # - method: GET request
      handler: exercise_get.main
      events:
      - http:
          path: exercises/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listExercises:
      # Defines an HTTP API endpoint that calls the main function in list.js
      # - path: url path is /exercises
      # - method: GET request
      handler: exercises_list.main
      events:
        - http:
            path: exercises
            method: get
            cors: true
            authorizer: aws_iam
  updateExercise:
      # Defines an HTTP API endpoint that calls the main function in update.js
      # - path: url path is /exercises/{id}
      # - method: PUT request
      handler: exercise_update.main
      events:
        - http:
            path: exercises/{id}
            method: put
            cors: true
            authorizer: aws_iam
  deleteExercise:
      # Defines an HTTP API endpoint that calls the main function in exercise_delete.js
      # - path: url path is /exercises/{id}
      # - method: DELETE request
      handler: exercise_delete.main
      events:
        - http:
            path: exercises/{id}
            method: delete
            cors: true
            authorizer: aws_iam
  listPlans:
        # Defines an HTTP API endpoint that calls the main function in plans_list.js
        # - path: url path is /plans
        # - method: GET request
        handler: plans_list.main
        events:
          - http:
              path: plans
              method: get
              cors: true
              authorizer: aws_iam
  createPlan:
          # Defines an HTTP API endpoint that calls the main function in plan_create.js
          # - path: url path is /plans
          # - method: POST request
          handler: plan_create.main
          events:
            - http:
                path: plans
                method: post
                cors: true
                authorizer: aws_iam
  getPlan:
          # Defines an HTTP API endpoint that calls the main function in plan_create.js
          # - path: url path is /plans
          # - method: POST request
          handler: plan_get.main
          events:
            - http:
                path: plans/{id}
                method: get
                cors: true
                authorizer: aws_iam
  updatePlan:
        # Defines an HTTP API endpoint that calls the main function in update.js
        # - path: url path is /plans/{id}
        # - method: PUT request
        handler: plan_update.main
        events:
          - http:
              path: plans/{id}
              method: put
              cors: true
              authorizer: aws_iam
  listTrainings:
          # Defines an HTTP API endpoint that calls the main function in plans_list.js
          # - path: url path is /plans
          # - method: GET request
          handler: trainings_list.main
          events:
            - http:
                path: trainings
                method: get
                cors: true
                authorizer: aws_iam
  createTraining:
            # Defines an HTTP API endpoint that calls the main function in plan_create.js
            # - path: url path is /plans
            # - method: POST request
            handler: training_create.main
            events:
              - http:
                  path: trainings
                  method: post
                  cors: true
                  authorizer: aws_iam
  getTraining:
            # Defines an HTTP API endpoint that calls the main function in plan_create.js
            # - path: url path is /plans
            # - method: POST request
            handler: training_get.main
            events:
              - http:
                  path: trainings/{id}
                  method: get
                  cors: true
                  authorizer: aws_iam
  updateTraining:
          # Defines an HTTP API endpoint that calls the main function in update.js
          # - path: url path is /plans/{id}
          # - method: PUT request
          handler: training_update.main
          events:
            - http:
                path: training/{id}
                method: put
                cors: true
                authorizer: aws_iam